# Generated by Django 5.1.1 on 2024-09-23 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='training_post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='video',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('training_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])])),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pamp_app.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTraining',
        ),
    ]
