# Generated by Django 5.1.1 on 2024-09-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0002_remove_profile_training_post_remove_profile_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
