# Generated by Django 5.1.1 on 2024-10-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly')], default='once', max_length=20)),
                ('days_of_week', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='pamp_app.profile')),
            ],
        ),
    ]
