# Generated by Django 5.1.1 on 2024-10-09 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0004_telegramlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlink',
            name='linking_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
