# Generated by Django 5.1.1 on 2024-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0006_remove_post_photo_remove_post_video_postimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
