# Generated by Django 5.1.1 on 2024-09-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0007_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
