# Generated by Django 5.1.1 on 2024-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0008_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/%Y/%m/%d/'),
        ),
    ]
